[package]
name = "arpc"
version = "0.1.0"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8"
actix-web = "1.0"
dotenv = "0.14"
postgres = { version = "0.15", features = ["with-chrono"] }
reqwest = { version = "0.9", features = ["socks"] }
chrono = "0.4"
crossbeam = "0.7"